### ISSUE TITLE
I'm wondering if the function(TableSubgroupMultiGLM) could support family = 'binomial( link = logit)".

### ISSUE THREAD

**Issue by chuckbyron** [jinseob2kim/jstable#19]
Dear author.thanks for your excellent R package, but i have one question:

I am analyzing cohort data, and I wish to analysis RR instead of OR value in subgroup analysis.

TableSubgroupMultiGLM(
  formula,
  var_subgroups = NULL,
  var_cov = NULL,
  data,
  family = "binomial",
  decimal.estimate = 2,
  decimal.percent = 1,
  decimal.pvalue = 3,
  line = F
)

I'm wondering if the function could support family = 'binomial( link = logit)".

thank u very much!

**Comment by jinseob2kim** [comment]
family = "binomial" is equal to family = 'binomial( link = logit)"

**Comment by chuckbyron** [comment]
> family = "binomial" is equal to family = 'binomial( link = logit)"

Dear author.thanks a lot for your reply. 

I hope to calculate the RR value, instead of OR value. When I use TableSubgroupMultiGLM() function, I got the OR value.  
And the readme file in your GitHub  also shows the OR value. Could you kindly support the methods to calculate RR value.

thans you very much, and best wishes!

**Comment by jinseob2kim** [comment]
Currently, `jsmodule` can't support RR(poisson or quasipoisson).
I will update RR until next CRAN release. 
Thanks for your feedback

**Comment by jinseob2kim** [comment]
I update RR to TableSubgroupMultiGLM 
* family: poisson or quasipoisson
please use the latest version via `remotes::install_github("jinseob2kim/jstable")`

**Comment by chuckbyron** [comment]
Thanks for your reply, and the updated package could calculate the RR value in poisson distribution regression.  But I still have one request, could you try to support log-binomial regression, sorry to bother you, I meant family = 'binomial( link = log)". 

Best wishes!

**Comment by jinseob2kim** [comment]
I've never used binomial(link=log) before. Can you share some example data and code?

**Comment by chuckbyron** [comment]
Thanks a lot, here are two websites use binomial(link=log) to calculate RR for log-binomial regression model. 

https://stackoverflow.com/questions/66593141/log-binomial-regression-for-binary-outcome-with-multiple-category-predictors-and

https://stats.oarc.ucla.edu/stata/faq/how-can-i-estimate-relative-risk-using-glm-for-common-outcomes-in-cohort-studies/

**Comment by jinseob2kim** [comment]
Thanks for the link. Sorry, I've never used the "log" option, so it's hard to apply.
