### ISSUE TITLE
sub-group analysis adjusted for other covariates

### ISSUE THREAD

**Issue by ayueme** [jinseob2kim/jstable#21]
Hello there,
   Sub-group analysis adjusted for other covariates is widely used in papers. For example, the figure 3 in this [paper](https://translational-medicine.biomedcentral.com/articles/10.1186/s12967-022-03839-0). 
![image](https://github.com/jinseob2kim/jstable/assets/58946586/2f9fc27a-326b-426a-9ced-de448c6b0fb3)

The TableSubgroupxxx functions can only have one covariate. Just like the following:
```
# OK
TableSubgroupMultiCox(
  formula = Surv(time, status) ~ rx, # only 1 covariates is supported
  var_subgroups = c("sex","age","obstruct","perfor","adhere"), 
  data = df)

# NOT OK
TableSubgroupMultiCox(
  formula = Surv(time, status) ~ rx + bmi + smoke, # this not work
  var_subgroups = c("sex","age","obstruct","perfor","adhere"), 
  data = df)
```
So would you mind adding this feature?
Thank you very much.

**Comment by jinseob2kim** [comment]
Please use `var_cov` option

**Comment by ayueme** [comment]
Thank you very much! I missed that important detail, sorry...
