### ISSUE TITLE
Cluster Option for TableSubgroupMultiCox

### ISSUE THREAD

**Issue by youmingmeia** [jinseob2kim/jstable#27]
Thank you, Jinseob Kim and jstable package maintainers, for providing such an effective package.  I wanted to bring to your attention a potential limitation in the TableSubgroupMultiCox function.  It appears that this function does not support the cluster option, making it unable to account for the presence of clustering effects when calculating the p-value for interaction.
In my research, I'm analyzing data with a cluster-correlated structure, and it's crucial to consider this correlation when assessing the significance of interactions.  However, the current implementation of TableSubgroupMultiCox does not provide this functionality.
Could you please clarify if there are plans to incorporate the cluster option in future updates?  Alternatively, if there's a workaround or an alternative approach within the package that can handle clustered data for interaction analysis, I would greatly appreciate your guidance.
Your contributions to the R community through the development and maintenance of the jstable package are invaluable, and I'm grateful for your expertise.

**Comment by jinseob2kim** [comment]
I update `cluster` option now. please use the latest package with `remotes::install_github("jinseob2kim/jstable")`

```r
library(survival)
library(dplyr)
lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(pat.karno >= 70)),
    kk1 = factor(as.integer(pat.karno >= 60))
  ) -> lung
TableSubgroupMultiCox(Surv(time, status) ~ sex,
  var_subgroups = c("kk", "kk1"),
  data = lung, time_eventrate = 100, line = TRUE, cluster = "inst"
)
```

**Comment by jinseob2kim** [comment]
But interaction P with 3 or more categorical variables can't be supported, because I can't run ANOVA when robust variance

**Comment by youmingmeia** [comment]
Thank you so much for your prompt response and for updating the package to include the cluster option. Your quick action and support mean a lot to me and my research.
I understand the limitation regarding interaction p-values for three or more categorical variables. Your explanation is clear, and I appreciate your transparency about this constraint.
Your dedication to improving the jstable package and supporting the R community is truly inspiring. Thank you again for your invaluable contributions.
