### ISSUE TITLE
jstable can't include subgroups(more than 3 levels)

### ISSUE THREAD

**Issue by XenonYang** [jinseob2kim/jstable#31]
[(https://cloud.tencent.com/developer/article/2319693)]

`rm(list = ls())
library(survival)

str(colon)
suppressMessages(library(tidyverse))

df <- colon %>% 
  mutate(rx=as.numeric(rx)) %>% 
  filter(etype == 1, !rx == 2) %>%  #rx %in% c("Obs","Lev+5FU"), 
  select(time, status,rx, sex, age,obstruct,perfor,adhere,differ,extent,surg,node4) %>% 
  mutate(sex=factor(sex, levels=c(0,1),labels=c("female","male")),
         age=ifelse(age >65,">65","<=65"),
         age=factor(age, levels=c(">65","<=65")),
         obstruct=factor(obstruct, levels=c(0,1),labels=c("No","Yes")),
         perfor=factor(perfor, levels=c(0,1),labels=c("No","Yes")),
         adhere=factor(adhere, levels=c(0,1),labels=c("No","Yes")),
         differ=factor(differ, levels=c(1,2,3),labels=c("well","moderate","poor")),
         extent=factor(extent, levels=c(1,2,3,4),
                       labels=c("submucosa","muscle","serosa","contiguous")),
         surg=factor(surg, levels=c(0,1),labels=c("short","long")),
         node4=factor(node4, levels=c(0,1),labels=c("No","Yes")),
         rx=ifelse(rx==3,0,1),
         rx=factor(rx,levels=c(0,1))
  )

str(df)

library(jstable)

res <- TableSubgroupMultiCox(
  formula = Surv(time, status) ~ rx, 
  var_subgroups = c("sex","age","obstruct","perfor","adhere",
                    "differ","extent","surg","node4"), 
  data = df 
)
res
`
The first line links to a person using the "jstable" for subgroup analysis, and its original code is under the link.
What I want to know is if I want to do a subgroup analysis, how to analyze the subgroup containing more than 2 categories. The above code runs in full. Sorry for the interruption.

**Comment by Ink-Mo** [comment]
I have the same problem:

 res <- TableSubgroupMultiCox(formula = Surv(time, Status) ~ group, 
+                              var_subgroups = c("Age","Hist","Grade","Stage"),
+                              data = df #指定你的数据
+                              )
Error in `purrr::map()`:
ℹ In index: 2.
Caused by error in `if (is.na(pv_anova) & !is.null(cluster)) ...`:
! the condition has length > 1
Run `rlang::last_trace()` to see where the error occurred.

**Comment by mfsd2a** [comment]
I encountered the similar issue, solved it by downgrading the version of jstable to 1.1.9.  Hope this information can help you.

**Comment by Ink-Mo** [comment]
> I encountered the similar issue, solved it by downgrading the version of jstable to 1.1.9. Hope this information can help you.

Downgrading to 1.1.9 still doesn't fix it

**Comment by jinseob2kim** [comment]
I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`

**Comment by XenonYang** [comment]
> I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`

I just downloaded the latest version and this problem has been solved, thank you very much!

**Comment by Ink-Mo** [comment]
> I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`

Yeah! It has been fixed. Thank you vary much!

**Comment by Cextra** [comment]
Hi, I tried updating the latest version,
 remotes::install_github(‘jinseob2kim/jstable’), 
but it still prompts 
Error in purrr::map(., ~survival::survfit(formula.km, data = .)) : 
  ℹ In index: 3.
ℹ With name: st.
Caused by error in `survfit.formula()`:

> I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`我解决了这个问题。请通过以下方式 `remotes::install_github("jinseob2kim/jstable")` 安装最新版本

**Comment by jinseob2kim** [comment]
> Hi, I tried updating the latest version, remotes::install_github(‘jinseob2kim/jstable’), but it still prompts Error in purrr::map(., ~survival::survfit(formula.km, data = .)) : ℹ In index: 3. ℹ With name: st. Caused by error in `survfit.formula()`:
> 
> > I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`我解决了这个问题。请通过以下方式 `remotes::install_github("jinseob2kim/jstable")` 安装最新版本

Could you share the example data and code?

**Comment by Cextra** [comment]
> Hi, I tried updating the latest version,嗨，我尝试更新最新版本， remotes::install_github(‘jinseob2kim/jstable’),remotes：：install_github（'jinseob2kim/jstable'）， but it still prompts但它仍然提示 Error in purrr::map(., ~survival::survfit(formula.km, data = .)) :purrr：：map（.， ~survival：：survfit（formula.km， data = .）） 中的错误： ℹ In index: 3.i 指数： 3. ℹ With name: st.i 名字：st。 Caused by error in `survfit.formula()`:由错误 `survfit.formula()` 引起：
> 
> > I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`我解决了这个问题。请通过以下方式 `remotes::install_github("jinseob2kim/jstable")` 安装最新版本

Sure
df <- aa %>% 
  select(time,status,group,age,BMI,hypertension,diabetes,ACS) %>% 
  mutate(status = as.integer(status == 1),
         age = ifelse(age <65,"<65",">=65"),
         age = factor(age, levels = c("<65",">=65")),
         BMI = ifelse(BMI <28,"<28", ">= 28"),
         BMI = factor(BMI, levels = c("<28", ">= 28")),
         hypertension = factor(hypertension, levels = c(0, 1), labels = c("No", "Yes")),
         diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes"))
         ACS=factor(ACS, levels=c(1,2,3,4),labels=c("non","ua","st","nst")))  
res <- TableSubgroupMultiCox(formula = Surv(time, status) ~ group,
                             var_subgroups = c("age","BMI","ACS"), 
                             var_cov = c("hypertension”,”diabetes"),
                             data = df)

**Comment by Cextra** [comment]
> > Hi, I tried updating the latest version, remotes::install_github(‘jinseob2kim/jstable’), but it still prompts Error in purrr::map(., ~survival::survfit(formula.km, data = .)) : ℹ In index: 3. ℹ With name: st. Caused by error in `survfit.formula()`:
> > > I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`我解决了这个问题。请通过以下方式 `remotes::install_github("jinseob2kim/jstable")` 安装最新版本
> 
> Could you share the example data and code?

Sure
df <- aa %>% 
  select(time,status,group,age,BMI,hypertension,diabetes,ACS) %>% 
  mutate(status = as.integer(status == 1),
         age = ifelse(age <65,"<65",">=65"),
         age = factor(age, levels = c("<65",">=65")),
         BMI = ifelse(BMI <28,"<28", ">= 28"),
         BMI = factor(BMI, levels = c("<28", ">= 28")),
         hypertension = factor(hypertension, levels = c(0, 1), labels = c("No", "Yes")),
         diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes")),
         ACS=factor(ACS, levels=c(1,2,3,4),labels=c("non","ua","st","nst")))  
res <- TableSubgroupMultiCox(formula = Surv(time, status) ~ group,
                             var_subgroups = c("age","BMI","ACS"), 
                             var_cov = c("hypertension”,”diabetes"),
                             data = df)

**Comment by jinseob2kim** [comment]
> > > Hi, I tried updating the latest version, remotes::install_github(‘jinseob2kim/jstable’), but it still prompts Error in purrr::map(., ~survival::survfit(formula.km, data = .)) : ℹ In index: 3. ℹ With name: st. Caused by error in `survfit.formula()`:
> > > > I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`我解决了这个问题。请通过以下方式 `remotes::install_github("jinseob2kim/jstable")` 安装最新版本
> > 
> > 
> > Could you share the example data and code?
> 
> Sure df <- aa %>% select(time,status,group,age,BMI,hypertension,diabetes,ACS) %>% mutate(status = as.integer(status == 1), age = ifelse(age <65,"<65",">=65"), age = factor(age, levels = c("<65",">=65")), BMI = ifelse(BMI <28,"<28", ">= 28"), BMI = factor(BMI, levels = c("<28", ">= 28")), hypertension = factor(hypertension, levels = c(0, 1), labels = c("No", "Yes")), diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes")), ACS=factor(ACS, levels=c(1,2,3,4),labels=c("non","ua","st","nst"))) res <- TableSubgroupMultiCox(formula = Surv(time, status) ~ group, var_subgroups = c("age","BMI","ACS"), var_cov = c("hypertension”,”diabetes"), data = df)

Please share the example data for reproducibility. I think the problem is "N of 3rd level group variable"

**Comment by Cextra** [comment]
[aa.xlsx](https://github.com/user-attachments/files/16330324/aa.xlsx)

**Comment by wognsths** [comment]
> [aa.xlsx](https://github.com/user-attachments/files/16330324/aa.xlsx)

The error was identified to occur while applying the subgroup option that some items in the subgroup did not exist in the data. The issue has been corrected. Please verify.

**Comment by Cextra** [comment]
> > [aa.xlsx](https://github.com/user-attachments/files/16330324/aa.xlsx)
> 
> The error was identified to occur while applying the subgroup option that some items in the subgroup did not exist in the data. The issue has been corrected. Please verify.在应用子组选项时，发现数据中不存在子组中的某些项目时发生错误。此问题已得到纠正。请验证。

Thanks, I corrected my mistake and was able to complete it without any problems
