### ISSUE TITLE
weights option for TableSubgroupMultiCox

### ISSUE THREAD

**Issue by youmingmeia** [jinseob2kim/jstable#32]
Hi prof. Jinseob Kim, thanks for your excellent work. The `TableSubgroupMultiCox` function in the `jstable` package has been extremely useful for my analyses, and I greatly appreciate the work you have put into developing it.
I am wondering if there are any plans to include a `weight` option within the `TableSubgroupMultiCox` function. This option would be very beneficial for analyses involving IPTW are necessary.

**Comment by jinseob2kim** [comment]
Currently, No coxph weight option in `TableSubgroupMultiCox`, But you can use weight with `svydesign` data. The below is example code (survey design)

```r
library(survival)
library(dplyr)
lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(pat.karno >= 70)),
    kk1 = factor(as.integer(pat.karno >= 60))
  ) -> lung
TableSubgroupMultiCox(Surv(time, status) ~ sex,
  var_subgroups = c("kk", "kk1"),
  data = lung, time_eventrate = 100, line = TRUE
)

## survey design
library(survey)
data.design <- svydesign(id = ~1, data = lung)
TableSubgroupMultiCox(Surv(time, status) ~ sex,
  var_subgroups = c("kk", "kk1"),
  data = data.design, time_eventrate = 100
)
```

**Comment by jinseob2kim** [comment]
I add `weights` option, please install the latest version via `remotes::install_github("jinseob2kim/jstable")`
