### ISSUE TITLE
Error in TableSubgroupMultiCox with cluster parameter

### ISSUE THREAD

**Issue by youmingmeia** [jinseob2kim/jstable#33]
When using the TableSubgroupMultiCox function with the cluster parameter, I encounter the following 
`library(jstable)
library(survival)
library(dplyr)

lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(pat.karno >= 70)),
    kk1 = factor(as.integer(pat.karno >= 60))
  ) -> lung

TableSubgroupMultiCox(
  Surv(time, status) ~ sex,
  var_subgroups = c("kk", "kk1"),
  data = lung,
  time_eventrate = 100,
  line = TRUE,
  cluster = "inst"
)
Error in get(cluster) : invalid first argument`

**Comment by jinseob2kim** [comment]
Sorry, I fix the issue. please install the latest version via `remotes::install_github("jinseob2kim/jstable")`
