### ISSUE TITLE
TableSubgroupMultiGLM 

### ISSUE THREAD

**Issue by Jone-wuy** [jinseob2kim/jstable#46]
Thank you for your excellent work; it is very convenient to use. However, I encountered a problem during the subgroup analysis process and need your help. Problem description: An error occurs in TableSubgroupMultiGLM when the covariates in var_cov contain categorical variables. The results for the subgroups are all empty, but the overall results are available.

Warning message: 1: In formula.character(object, env = baseenv()): Using formula(x) is deprecated when x is a character vector of length > 1. Consider formula(paste(x, collapse = " ")) instead. I tried a few times and there is no problem when categorical variables are not included in the covariates, but once categorical covariates are added, an error is reported.

**Comment by Jone-wuy** [comment]
Thank you for your response. 
I tried your suggestion, but it didn't resolve the issue. Here is my case: when I don't include categorical covariates, the results are fine. However, when I include categorical covariates, the subgroup results turn out to be NA. 
Below are the run results, and the attachment contains my case data.

Thank you very much！

data <-data %>%
  mutate(status = as.integer(status==1),
         sex=factor(sex),
         pa_d=factor(pa_d),
         diet_d=factor(diet_d))
res1 <- TableSubgroupMultiGLM(formula=status~ln_oh,
                             var_subgroups = c("pa_d", "diet_d"),
                             data=data, 
                             var_cov = c("age", "bmi"),
                             family = "binomial",
                             decimal.estimate = 2,
> res1
      Variable Count Percent   OR Lower Upper P value P for interaction
ln_oh  Overall  1200     100 1.17   0.9  1.52   0.247              <NA>
1         pa_d  <NA>    <NA> <NA>  <NA>  <NA>      NA             0.069
2            1   600      50 0.81  0.51  1.28   0.372              <NA>
3            2   600      50 1.32  0.95  1.83   0.097              <NA>
4       diet_d  <NA>    <NA> <NA>  <NA>  <NA>      NA             0.539
5            1   600      50 1.02  0.63  1.64    0.95              <NA>
6            2   600      50 1.17  0.85  1.62   0.336              <NA>

res2 <- TableSubgroupMultiGLM(formula=status~ln_oh,
                             var_subgroups = c("pa_d", "diet_d"),
                             data=data, 
                             var_cov = c("age", "bmi","sex"),
                             family = "binomial",
                             decimal.estimate = 2,
                             decimal.percent = 1,
                             decimal.pvalue = 3)
> res2
      Variable Count Percent   OR Lower Upper P value P for interaction
ln_oh  Overall  1200     100 1.36  1.03   1.8   0.028              <NA>
1         pa_d  <NA>    <NA> <NA>  <NA>  <NA>    <NA>             0.119
2            1   600      50 <NA>  <NA>  <NA>    <NA>              <NA>
3            2   600      50 <NA>  <NA>  <NA>    <NA>              <NA>
4       diet_d  <NA>    <NA> <NA>  <NA>  <NA>    <NA>             0.547
5            1   600      50 <NA>  <NA>  <NA>    <NA>              <NA>
6            2   600      50 <NA>  <NA>  <NA>    <NA>              <NA>

[data_example.csv](https://github.com/user-attachments/files/17101469/data_example.csv)

**Comment by jinseob2kim** [comment]
Sorry. I fix the issue. Please install the latest version via
```r
remotes::install_github(“jinseob2kim/jstable”)
```

**Comment by Jone-wuy** [comment]
Thank you for your fix. The issue has been perfectly resolved. Thanks again for your outstanding work!
