### ISSUE TITLE
Using glmer in TableSubgroupMultiGLM

### ISSUE THREAD

**Issue by Hejiewang** [jinseob2kim/jstable#55]
I want glmer to analyze the association between gender and anemia and take pro as a random item, and I wonder if the TableSubgroupMultiGLM function can use glmer to create a table for subgroup analysis? In addition, if I use the following code for analysis, the same prompt, I want to know how to fix this question, The used jstable package is the newest.
In formula.character(object, env = baseenv()) :
Using formula(x) is deprecated when x is a character vector of length > 1.
 My code is here: 
China_data<-binary_China_data%>%
  select(SEX,NA13,NA14,nA4b,AA6,BG9,group_age,motherage,binary_anemia,pro))%>%
  mutate(SEX=factor(SEX,levels=c(1,2),labels=c("Male","Female")),
         NA13=factor(NA13,levels=c(0,1),labels=c("Improved water source","Unimproved water source")),
         NA14=factor(NA14,levels=c(0,1),labels=c("Improved sanitation","Unimproved sanitation")),
         nA4b=factor(nA4b,levels=c(0,1,2),labels=c("Primary","Secondary","Higher")),
         AA6=factor(AA6,levels=c(0,1),labels=c("<3","≥3")),BG9=factor(BG9,levels=c(0,1),labels=c("No secondhand smoking","Second smoking")),  group_age=factor(group_age,levels=c(0,1,2,3,4),labels=c("6~11 months","12-23 mongths","24-35 months","36-47 months","48-59 months")), motherage=factor(motherage,levels=c(0,1),labels=c("No","Yes")),
         pro=factor(pro,levels=c(15,32,37,44,52),labels=c("Inner Mongolia","Jiangsu","Shandong","Guangdong","Guizhou")))
var<-c("AA6","BG9","group_age","pro")
res<-TableSubgroupMultiGLM(binary_anemia~SEX,var_cov = c("AA6","NA14","motherage","group_age","pro"),
                           var_subgroups = var,data=China_data,family = "binomial")

**Comment by jinseob2kim** [comment]
Sorry, the function can`t support glmer/lmer now. I will update the function soon.

**Comment by sl-eeper** [comment]
I have reviewed the functionality of the TableSubgroupMultiGLM function and made updates to ensure compatibility with both glm and glmer models. Here’s a summary of the changes I implemented and how they address your requirements:

Support for glmer Models:

I extended the TableSubgroupMultiGLM function to handle mixed-effects models (glmer) with random effects, such as (1|pro), enabling subgroup analysis with random grouping variables.
Streamlined Subgroup Analysis:

The function now supports subgroup-specific analyses for variables specified in var_subgroups, regardless of whether the model is glm or glmer.
Reproducing Results:

I verified the functionality using a simulated dataset (lung from the survival package) with multiple configurations, including:
Simple logistic regression (glm with family = "binomial").
Mixed-effects logistic regression (glmer with random effects).
Gaussian family models for continuous outcomes.
Subgroup analyses with categorical covariates.
Example Code: Below is an example demonstrating how the updated function works:

R
코드 복사
library(survival)
library(dplyr)
library(jstable)

lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(as.numeric(as.character(pat.karno)) > 70))
  ) -> lung

lung.label <- mk.lev(lung)

# Logistic regression (glm)
TableSubgroupGLM(status ~ sex, data = lung, labeldata = lung.label, family = "binomial")

# Mixed-effects logistic regression (glmer)
TableSubgroupGLM(status ~ sex + (1 | inst), data = lung, labeldata = lung.label, family = "binomial")

# Subgroup analysis with glmer
TableSubgroupGLM(status ~ sex + (1 | inst), var_subgroup = "ph.ecog", data = lung, labelda


I have made pulled request so you may be able to use it by using remotes::install_github("jinseob2kim/jstable") after the request is merged.

**Comment by Hejiewang** [comment]
Thanks for your help, it is very useful.
