### ISSUE TITLE
Not work for more than 2 categories

### ISSUE THREAD

**Issue by Arkxiao** [jinseob2kim/jstable#57]
>overall <- within(overall, {
  Tumor_location<-factor(TumorLocation, levels=c(1,2,3),labels =c("Upper third","Middle third","Lower third"))
})
> summary(overall$Tumor_location)
 Upper third Middle third  Lower third 
         115          140           75 
> library(jstable)
> res.OS<-TableSubgroupMultiCox(
+   formula=Surv(OStime,OSstatus)~IntentToTreat,
+   var_subgroups=c("Tumor_location"),
+   data=overall
+ )
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `if (is.na(pv_anova) & !is.null(cluster)) ...`:
! the condition has length > 1
Run `rlang::last_trace()` to see where the error occurred.
>  res.OS<-TableSubgroupMultiCox(
+   formula=Surv(OStime,OSstatus)~IntentToTreat,
+   var_subgroups=c("Sex"),
+   data=overall
+ )
> res.OS
               Variable Count Percent Point Estimate Lower Upper IntentToTreat=RT IntentToTreat=CRT+CT P value P for interaction
IntentToTreat   Overall   330     100           0.75  0.58  0.96             80.5                   73   0.024              <NA>
1                   Sex  <NA>    <NA>           <NA>  <NA>  <NA>             <NA>                 <NA>    <NA>             0.351
2                  Male   220    66.7           0.67  0.49  0.91             83.8                 76.5    0.01              <NA>
3                Female   110    33.3           0.86  0.55  1.36             75.3                   66   0.519              <NA>

The code worded for 2 Categorical variables but not for 3 Categorical variables. Expect for answers.

**Comment by jinseob2kim** [comment]
Can you share the data? I can run the function with 3 Categorical variables. (below code)

```r
library(survival);library(dplyr)
lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(pat.karno >= 70)),
    kk1 = factor(as.integer(pat.karno >= 60))
  ) -> lung

lung$ph.ecog <- factor(lung$ph.ecog)

TableSubgroupMultiCox(Surv(time, status) ~ sex,
                 var_subgroups = "ph.ecog", data = lung)


```

**Comment by Arkxiao** [comment]
Thanks for the reply！


I finally run the function after restarting the R studio.






祝您身体健康，工作顺利！




常笑
Xiao Chang
北京大学肿瘤医院／北京市肿瘤防治研究所
Beijing Cancer Hospital & Beijing Institute For Cancer Research
Mobile:+86-18801067622
***@***.***
Address:北京市海淀区阜成路52号北京大学肿瘤医院放疗科，邮编：100142
Department of Radiation Oncology  
Beijing Cancer Hospital ，No. 52, Fucheng Road， Haidian District, Beijing, 100142




---- Replied Message ----
| From | Jinseob ***@***.***> |
| Date | 11/29/2024 09:49 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [jinseob2kim/jstable] Not work for more than 2 categories (Issue #57) |

Can you share the data? I can run the function with 3 Categorical variables. (below code)

library(survival);library(dplyr)
lung %>%
  mutate(
    status= as.integer(status==1),
    sex=factor(sex),
    kk=factor(as.integer(pat.karno>=70)),
    kk1=factor(as.integer(pat.karno>=60))
  ) ->lunglung$ph.ecog<-factor(lung$ph.ecog)

TableSubgroupMultiCox(Surv(time, status) ~sex,
                 var_subgroups="ph.ecog", data=lung)
