### ISSUE TITLE
Why the number is not integer?

### ISSUE THREAD

**Issue by xiasijian** [jinseob2kim/jstable#61]
![image](https://github.com/user-attachments/assets/7481fa41-f8f2-4d70-ad02-cdcc44960646)

my code:

`res_os <- TableSubgroupMultiCox(
  
  formula = Surv(LRFS, LRFS_status) ~ group, 
  
  var_subgroups = c("age","gender"), 
  data = df
)`

**Comment by jinseob2kim** [comment]
This is KM estimate incidence(%) at `time_eventrate`(default: 3 * 365)

**Comment by xiasijian** [comment]
Thanks a lot, it is a very good package for doctor. how can I get the patient number of each group when using subgroup cox regression?

**Comment by jinseob2kim** [comment]
Count is N

**Comment by xiasijian** [comment]
thanks, But it is not the number of "group=low" and "group=high"

**Comment by sl-eeper** [comment]
Hi, I recently updated this option.

```{r}
lung %>%
  mutate(
    status = as.integer(status == 1),
    sex = factor(sex),
    kk = factor(as.integer(pat.karno >= 70)),
    kk1 = factor(as.integer(pat.karno >= 60))
  ) -> lung

lung.label <- mk.lev(lung)

lung.label <- lung.label %>%
  mutate(
    val_label = case_when(
      variable == "sex" & level == "1" ~ "Male",
      variable == "sex" & level == "2" ~ "Female",
      variable == "kk" & level == "0" ~ "No",
      variable == "kk" & level == "1" ~ "Yes",
      variable == "kk1" & level == "0" ~ "No",
      variable == "kk1" & level == "1" ~ "Yes",
      TRUE ~ val_label
    )
  )
TableSubgroupMultiCox(Surv(time, status) ~ sex, 
                      var_subgroups = c("kk", "kk1"), 
                      data = lung, 
                      time_eventrate = 100, 
                      line = TRUE, 
                      cluster = "inst", 
                      strata = "inst", 
                      weights = "age", 
                      event = FALSE, 
                      count_by = "sex", 
                      labeldata = lung.label)
  ```
Result will look like:
| Variable | Count | Count(sex=Male) | Count(sex=Female) | Percent | Point Estimate | Lower       | Upper       | sex=1 | sex=2 | P value | P for interaction |
|----------|-------|-----------------|-------------------|---------|----------------|-------------|-------------|-------|-------|---------|-------------------|
| sex      | 227   | 138             | 90                | 100     | 1.66           | 1.09        | 2.53        | 0     | 1.2   | 0.019   | <NA>              |
| 1        | <NA>  | <NA>            | <NA>              | <NA>    | <NA>           | <NA>        | <NA>        | <NA>  | <NA>  | <NA>    | <NA>              |
| 2        | kk    | <NA>            | <NA>              | <NA>    | <NA>           | <NA>        | <NA>        | <NA>  | <NA>  | 0.562   | <NA>              |
| 3        | No    | 38              | 22                | 16      | 193294637.42   | 27228158.02 | 1372212428.98 | 0     | 0     | <0.001  | <NA>              |
| 4        | Yes   | 186             | 114               | 73      | 1.44           | 0.95        | 2.18        | 0     | 1.5   | 0.084   | <NA>              |
| 5        | <NA>  | <NA>            | <NA>              | <NA>    | <NA>           | <NA>        | <NA>        | <NA>  | <NA>  | <NA>    | <NA>              |
| 6        | kk1   | <NA>            | <NA>              | <NA>    | <NA>           | <NA>        | <NA>        | <NA>  | <NA>  | <0.001  | <NA>              |
| 7        | No    | 8               | 4                 | 4       | <NA>           | <NA>        | <NA>        | 0     | 0     | <NA>    | <NA>              |
| 8        | Yes   | 216             | 132               | 85      | 1.55           | 1           | 2.41        | 0     | 1.3   | 0.049   | <NA>              |




You can use the Count = 'variable' option to display counts by each variable. Additionally, by adding the Event = TRUE option, you can obtain the raw event rate values (which are not Kaplan-Meier estimates).

**Comment by xiasijian** [comment]
Thanks a lot!



---Original---
From: "Hyungwoo ***@***.***&gt;
Date: Mon, Dec 9, 2024 12:58 PM
To: ***@***.***&gt;;
Cc: "Sijian ***@***.******@***.***&gt;;
Subject: Re: [jinseob2kim/jstable] Why the number is not integer? (Issue #61)




 
Hi, I recently updated this option.
 lung %&gt;%   mutate(     status = as.integer(status == 1),     sex = factor(sex),     kk = factor(as.integer(pat.karno &gt;= 70)),     kk1 = factor(as.integer(pat.karno &gt;= 60))   ) -&gt; lung lung.label <- mk.lev(lung) lung.label <- lung.label %&gt;%   mutate(     val_label = case_when(       variable == "sex" &amp; level == "1" ~ "Male",       variable == "sex" &amp; level == "2" ~ "Female",       variable == "kk" &amp; level == "0" ~ "No",       variable == "kk" &amp; level == "1" ~ "Yes",       variable == "kk1" &amp; level == "0" ~ "No",       variable == "kk1" &amp; level == "1" ~ "Yes",       TRUE ~ val_label     )   ) TableSubgroupMultiCox(Surv(time, status) ~ sex,                        var_subgroups = c("kk", "kk1"),                        data = lung,                        time_eventrate = 100,                        line = TRUE,                        cluster = "inst",                        strata = "inst",                        weights = "age",                        event = FALSE,                        count_by = "sex",                        labeldata = lung.label)  
Result will look like:
    Variable Count Count(sex=Male) Count(sex=Female) Percent Point Estimate Lower Upper sex=1 sex=2 P value P for interaction 
    sex 227 138 90 100 1.66 1.09 2.53 0 1.2 0.019  
  1            
  2 kk         0.562  
  3 No 38 22 16 193294637.42 27228158.02 1372212428.98 0 0 <0.001  
  4 Yes 186 114 73 1.44 0.95 2.18 0 1.5 0.084  
  5            
  6 kk1         <0.001  
  7 No 8 4 4    0 0   
  8 Yes 216 132 85 1.55 1 2.41 0 1.3 0.049  
   
You can use the Count = 'variable' option to display counts by each variable. Additionally, by adding the Event = TRUE option, you can obtain the raw event rate values (which are not Kaplan-Meier estimates).
